# Generated by Django 4.0.4 on 2022-07-01 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_store_custo_last_na_e6a359_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='promotion',
            new_name='promotions',
        ),
    ]
