# Generated by Django 4.0.6 on 2022-08-06 19:33

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='taggeditem',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
